### ISSUE TITLE
Include fails if it depends on yaybu.argv.foo

### ISSUE THREAD

**Issue by Jc2k** [yaybu/yaybu#102]
The following doesn't work:

```
yaybu:
    options:
        - name: foo
          default: bar.yay

include yaybu.argv.foo
```

But the following does:

```
include yaybu.argv.foo

yaybu:
    options:
        - name: foo
          default: bar.yay
```

In the former, Yay needs to be able to resolve yaybu.argv.foo in order to look at the directives before the include. But it needs those directives before it can resolve yaybu.argv.foo, as they define the default values for yaybu.argv.foo!.

In the latter, yaybu.options is definitely provably known so it isn't a problem and works as is.

I think porting the argument parser to be "lazy" would resolve this problem as their is already an optimistic peek-behind and booby-trap arrangement for "standard" variables.
