### ISSUE TITLE
Doesn't account for local file copying in simulate mode

### ISSUE THREAD

**Issue by Jc2k** [yaybu/yaybu#68]
Test case:

```
resources.append:
    - File:
          name: /tmp/blah

    - File:
          name: /tmp/blah2
          static: /tmp/blah
```

Missing assets should be a warning if they start with '/' as they might be created by earlier parts of simulate.
