### ISSUE TITLE
add command line args passing to config

### ISSUE THREAD

**Issue by winjer** [yaybu/yaybu#90]
syntax:
provision <provider> <cluster> <filename> name=value name=value name=value

**Comment by Jc2k** [comment]
This will need to be applied to the push and apply commands as well, i think.

Version 1 would just split on '=', make sure the name was a valid yay key and shove it under yaybu.argv.

Version 2 would have some sort of schema mechanism that would validate things before allowing them into yaybu.argv.

Something like:

```
yaybu:
    argv:
        sitename:
            value: # This will be injected by yaybu
            type: text
            description: This is the primary url of the site - e.g. www.foo.com
```
